name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Cache Key
      id: cache_key
      run: echo ::set-output name=key::$(md5sum stack.yaml | awk '{print $1}')

    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ steps.cache_key.outputs.key }}

    - name: Build Snapshot
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        stack --no-terminal test --bench --only-snapshot

    - name: Build & Test
      run: |
        stack --no-terminal test --bench --no-run-benchmarks
        stack install
        mkdir dist
        cp $HOME/.local/bin/mqttd dist

    - name: Store Artifact
      uses: actions/upload-artifact@v1
      with:
        name: mqttd-${{ matrix.os }}
        path: dist

    - name: Build Docs
      if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'
      run: |
        stack --no-terminal haddock --no-haddock-deps
        stack install
        PKG_NAME=$(cat *.cabal | grep "name:" | sed "s/name:\s*\(.*\)/\1/")
        mkdir -p docs && mv $(stack path --local-install-root)/doc/$PKG_NAME-*/* docs/

    - name: Publish Docs
      if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        enable_jekyll: false
