name: "Nix Build"
on:
  push:
    branches:
      - master
  schedule:
  - cron: "3 11 13,27 * *"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: dustin
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A mqttd.components.exes.mqttd
    - run: nix-build -A mqttd.components.exes.mqttdpass
    - run: nix-build -A mqttd.components.tests.mqttd-test
    - run: nix-shell -p ./result --run mqttd-test
