name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v6
      with:
        name: dustin
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A mqttd.components.exes.mqttd
    - run: nix-build -A mqttd.components.tests.mqttd-test
    - run: nix-shell -p ./result --run mqttd-test
